name = "MetX_Registry_jl"
uuid = "1c72429a-3511-4c8d-85f7-40c1dbddce41"
repo = "https://github.com/MetabolicXploration/MetX_Registry_jl"
description = "A local registry for non General packages"

[packages]
01815447-a018-4668-9805-89f51b3fc6a1 = { name = "MetX", path = "M/MetX" }
0b8c4419-604a-4c8e-9eed-0f79de4a140e = { name = "MetXBase", path = "M/MetXBase" }
33338342-c6de-4489-9d80-13def6a0398d = { name = "MetXGrids", path = "M/MetXGrids" }
3facea42-c6d8-46ab-8896-2657a92d9f87 = { name = "MetXEP", path = "M/MetXEP" }
672bf490-d3aa-44fe-a664-43445036b9de = { name = "MetXOptim", path = "M/MetXOptim" }
aeeda050-7d39-4c85-b6eb-65567cadcf4d = { name = "RunTestsEnv", path = "R/RunTestsEnv" }
be9415a8-24b2-49ae-ba75-41eeaa9f722f = { name = "MetXNetHub", path = "M/MetXNetHub" }
bfe2832f-5600-46d7-a449-140889a58637 = { name = "StringRepFilter", path = "S/StringRepFilter" }
c8a5ff98-18da-494d-98cc-f2d3bae7da4c = { name = "MetXCultureHub", path = "M/MetXCultureHub" }
c9719566-2c26-451b-95bc-5aa9e2747dfa = { name = "NDHistograms", path = "N/NDHistograms" }
d4a97fa3-1e77-4085-814f-98651929ce7d = { name = "MetXMC", path = "M/MetXMC" }
